[package]
name = "equilibrium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
rand = "0.8.4"
noise = "0.7.0"
geo = "0.18.0"
eframe = "0.16.0"
project-root = "0.2.2"
